**BIG BIG HINT! Look in the instructions to guide you on this task.**

In [46]:
# Dependencies
import pandas as pd

In [47]:
# load CSV
csv_path = "Resources/2016-FCC-New-Coders-Survey-Data.csv"

In [48]:
# Read with pandas
dataunclean_df = pd.read_csv(csv_path, low_memory=False)
dataunclean_df.head()

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampMonthsAgo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,...,ResourceSoloLearn,ResourceStackOverflow,ResourceTreehouse,ResourceUdacity,ResourceUdemy,ResourceW3Schools,ResourceYouTube,SchoolDegree,SchoolMajor,StudentDebtOwe
0,28.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,20000.0
1,22.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,"some college credit, no degree",NaN,NaN
2,19.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high school diploma or equivalent (GED),NaN,NaN
3,26.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bachelor's degree,Cinematography And Film,7000.0
4,20.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,NaN

In [49]:
# Inspect all columns
for col in dataunclean_df.columns: 
    print(col)

Age
AttendedBootcamp
BootcampFinish
BootcampFullJobAfter
BootcampLoanYesNo
BootcampMonthsAgo
BootcampName
BootcampPostSalary
BootcampRecommend
ChildrenNumber
CityPopulation
CodeEventBootcamp
CodeEventCoffee
CodeEventConferences
CodeEventDjangoGirls
CodeEventGameJam
CodeEventGirlDev
CodeEventHackathons
CodeEventMeetup
CodeEventNodeSchool
CodeEventNone
CodeEventOther
CodeEventRailsBridge
CodeEventRailsGirls
CodeEventStartUpWknd
CodeEventWomenCode
CodeEventWorkshop
CommuteTime
CountryCitizen
CountryLive
EmploymentField
EmploymentFieldOther
EmploymentStatus
EmploymentStatusOther
ExpectedEarning
FinanciallySupporting
Gender
HasChildren
HasDebt
HasFinancialDependents
HasHighSpdInternet
HasHomeMortgage
HasServedInMilitary
HasStudentDebt
HomeMortgageOwe
HoursLearning
ID.x
ID.y
Income
IsEthnicMinority
IsReceiveDiabilitiesBenefits
IsSoftwareDev
IsUnderEmployed
JobApplyWhen
JobPref
JobRelocateYesNo
JobRoleInterest
JobRoleInterestOther
JobWherePref
LanguageAtHome
MaritalStatus
MoneyForLearning
MonthsProgramming
NetworkID
Part1EndTime
Part1StartTime
Part2EndTime
Part2StartTime
PodcastChangeLog
PodcastCodeNewbie
PodcastCodingBlocks
PodcastDeveloperTea
PodcastDotNetRocks
PodcastHanselminutes
PodcastJSJabber
PodcastJsAir
PodcastNone
PodcastOther
PodcastProgrammingThrowDown
PodcastRubyRogues
PodcastSEDaily
PodcastShopTalk
PodcastTalkPython
PodcastWebAhead
ResourceBlogs
ResourceBooks
ResourceCodeWars
ResourceCodecademy
ResourceCoursera
ResourceDevTips
ResourceEdX
ResourceEggHead
ResourceFCC
ResourceGoogle
ResourceHackerRank
ResourceKhanAcademy
ResourceLynda
ResourceMDN
ResourceOdinProj
ResourceOther
ResourcePluralSight
ResourceReddit
ResourceSkillCrush
ResourceSoloLearn
ResourceStackOverflow
ResourceTreehouse
ResourceUdacity
ResourceUdemy
ResourceW3Schools
ResourceYouTube
SchoolDegree
SchoolMajor
StudentDebtOwe

In [58]:
# Extract only columns 0, 1, 2, 3, 4, 7, 8, 9, 10, 11, 29, 30, 32, 36, 37, 45, 48, 56, 110, 111


dataclean_df = dataunclean_df.iloc[:,[0, 1, 2, 3, 4, 7, 8, 9, 10, 11, 29, 30, 32, 36, 37, 45, 48, 56, 110, 111]]
dataclean_df

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventBootcamp,CountryLive,EmploymentField,EmploymentStatus,Gender,HasChildren,HoursLearning,Income,JobRoleInterest,SchoolDegree,SchoolMajor
0,28.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,office and administrative support,Employed for wages,male,0.0,30.0,32000.0,NaN,"some college credit, no degree",NaN
1,22.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,food and beverage,Employed for wages,male,NaN,30.0,15000.0,Front-End Web Developer,"some college credit, no degree",NaN
2,19.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,finance,Employed for wages,male,NaN,20.0,48000.0,NaN,high school diploma or equivalent (GED),NaN
3,26.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,NaN,20.0,43000.0,Front-End Web Developer,bachelor's degree,Cinematography And Film
4,20.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,education,Employed for wages,female,NaN,25.0,6000.0,Full-Stack Web Developer,"some college credit, no degree",NaN
5,34.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,finance,Self-employed freelancer,male,NaN,5.0,40000.0,NaN,bachelor's degree,English
6,23.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Singapore,software development,Employed for wages,male,NaN,8.0,32000.0,NaN,bachelor's degree,Computer Science
7,35.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United Kingdom,office and administrative support,Employed for wages,male,0.0,NaN,40000.0,NaN,master's degree (non-professional),Education
8,33.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Employed for wages,male,NaN,5.0,80000.0,NaN,bachelor's degree,Business Administration
9,33.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,NaN,Employed for wages,male,NaN,20.0,80000.0,NaN,master's degree (non-professional),Business Administration
10,57.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,United States of America,NaN,Self-employed business owner,male,0.0,8.0,20000.0,NaN,bachelor's degree,Computer Science
11,23.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Bangladesh,NaN,Not working and not looking for work,male,NaN,5.0,NaN,NaN,"some college credit, no degree",NaN
12,47.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Canada,health care,Employed for wages,male,NaN,5.0,90000.0,NaN,bachelor's degree,Mechanical Engineering
13,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Employed for wages,male,NaN,5.0,NaN,NaN,bachelor's degree,Business Administration
14,37.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,"between 100,000 and 1 million",NaN,Bosnia & Herzegovina,sales,Self-employed business owner,male,1.0,2.0,NaN,NaN,"some college credit, no degree",NaN
15,31.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Russia,software development,Employed for wages,female,NaN,10.0,NaN,NaN,"professional degree (MBA, MD, JD, etc.)",Math
16,27.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,software development,Employed for wages,female,NaN,4.0,80000.0,NaN,bachelor's degree,Economics
17,29.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,United States of America,education,Employed for wages,male,NaN,5.0,17000.0,NaN,bachelor's degree,Music
18,30.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Canada,software development,Self-employed freelancer,male,NaN,2.0,16000.0,NaN,bachelor's degree,Music
19,30.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,Croatia,NaN,Not working but looking for work,male,0.0,20.0,NaN,Full-Stack Web Developer,"some college credit, no degree",NaN
20,32.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,more than 1 million,NaN,United States of America,NaN,Employed for wages,female,1.0,5.0,200000.0,Full-Stack Web Developer,master's degree (non-professional),Geology
21,25.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Doing an unpaid internship,female,NaN,NaN,NaN,NaN,bachelor's degree,Computer Science
22,29.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,0.0,10.0,100000.0,NaN,bachelor's degree,Computer Science
23,44.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,office and administrative support,Employed for wages,female,0.0,30.0,41000.0,NaN,bachelor's degree,Political Science
24,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,India,NaN,Not working but looking for work,male,NaN,25.0,NaN,NaN,bachelor's degree,Computer Science
25,21.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Not working but looking for work,male,NaN,25.0,NaN,Full-Stack Web Developer,"some college credit, no degree",NaN
26,28.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,South Africa,NaN,Self-employed freelancer,male,0.0,1.0,12000.0,NaN,high school diploma or equivalent (GED),NaN
27,28.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,more than 1 million,NaN,United States of America,software development,Employed for wages,male,1.0,10.0,60000.0,NaN,"trade, technical, or vocational training",NaN
28,25.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Employed for wages,male,NaN,10.0,75000.0,Full-Stack Web Developer,bachelor's degree,Political Science
29,35.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,"less than 100,000",NaN,United Kingdom,software development,Employed for wages,male,1.0,5.0,35000.0,NaN,master's degree (non-professional),Physics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15590,25.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,male,NaN,2.0,200000.0,NaN,bachelor's degree,Computer Science
15591,25.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Brazil,software development and IT,Employed for wages,male,0.0,2.0,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Computer Systems Networking and Telecommunicat...
15592,43.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,male,1.0,3.0,200000.0,NaN,high school diploma or equivalent (GED),NaN
15593,29.0,1.0,0.0,NaN,0.0,NaN,0.0,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,female,0.0,5.0,200000.0,NaN,bachelor's degree,Accounting
15594,36.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,more than 1 million,NaN,United States of America,finance,Employed for wages,male,1.0,1.0,200000.0,NaN,bachelor's degree,Engineering
15595,30.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Ukraine,software development and IT,Self-employed freelancer,male,0.0,30.0,200000.0,NaN,some high school,NaN
15596,30.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,"less than 100,000",NaN,Brazil,software development and IT,Employed for wages,male,1.0,2.0,200000.0,NaN,high school diploma or equivalent (GED),NaN
15597,30.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Ukraine,legal,Self-employed freelancer,male,NaN,6.0,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Law
15598,28.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,"less than 100,000",NaN,United States of America,food and beverage,Employed for wages,male,1.0,20.0,200000.0,Full-Stack Web Developer,associate's degree,Computer and Information Systems Security
15599,37.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,male,NaN,5.0,200000.0,NaN,"some college credit, no degree",NaN
15600,28.0,1.0,1.0,1.0,0.0,36000.0,1.0,NaN,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,female,NaN,8.0,200000.0,NaN,bachelor's degree,Marketing
15601,25.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,legal,Employed for wages,male,NaN,10.0,200000.0,NaN,bachelor's degree,Criminal Justice and Safety Studies
15602,22.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,India,software development and IT,Employed for wages,male,NaN,50.0,200000.0,Data Scientist / Data Engineer,bachelor's degree,Mathematics
15603,33.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,software development and IT,Employed for wages,male,NaN,4.0,200000.0,NaN,bachelor's degree,Computer Science
15604,35.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,Norway,construction and extraction,Employed for wages,male,NaN,5.0,200000.0,Front-End Web Developer,"some college credit, no degree",NaN
15605,31.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Portugal,software development and IT,Employed for wages,male,NaN,5.0,200000.0,Full-Stack Web Developer,high school diploma or equivalent (GED),NaN
15606,43.0,0.0,NaN,NaN,NaN,NaN,NaN,3.0,more than 1 million,NaN,Canada,legal,Self-employed business owner,male,1.0,3.0,200000.0,NaN,bachelor's degree,Physics
15607,25.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Philippines,software development,Self-employed freelancer,male,0.0,8.0,200000.0,NaN,no high school (secondary school),NaN
15608,43.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,more than 1 million,NaN,United States of America,health care,Employed for wages,male,1.0,6.0,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Electrical Engineering
15609,33.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Mexico,software development and IT,Employed for wages,male,0.0,16.0,200000.0,NaN,bachelor's degree,Software Engineering
15610,29.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,education,Employed for wages,male,NaN,5.0,200000.0,Front-End Web Developer,master's degree (non-professional),Religious Studies
15611,37.0,0.0,NaN,NaN,NaN,NaN,NaN,1.0,more than 1 million,NaN,Canada,software development and IT,Self-employed business owner,male,1.0,40.0,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Electrical and Electronics Engineering
15612,45.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Employed for wages,female,NaN,2.0,200000.0,NaN,"some college credit, no degree",NaN
15613,30.0,0.0,NaN,NaN,NaN,NaN,NaN,2.0,more than 1 million,NaN,South Africa,software development and IT,Employed for wages,male,1.0,4.0,200000.0,NaN,"trade, technical, or vocational training",NaN
15614,47.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,finance,Employed for wages,male,NaN,3.0,26000.0,NaN,"trade, technical, or vocational training",NaN
15615,39.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Kenya,software development and IT,Self-employed freelancer,male,0.0,40.0,10000.0,NaN,bachelor's degree,Chemistry
15616,27.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,male,0.0,15.0,10000.0,Front-End Web Developer,bachelor's degree,Electrical Engineering
15617,37.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Nigeria,NaN,Self-employed freelancer,male,NaN,14.0,48000.0,NaN,bachelor's degree,Chemistry
15618,26.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Spain,education,Self-employed freelancer,male,NaN,10.0,10000.0,NaN,master's degree (non-professional),Math
15619,22.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,0.0,2.0,18000.0,NaN,bachelor's degree,Graphic Design

In [60]:
# Change "0" to "No" and "1" to "Yes" in response columns
dataclean_df = dataclean_df.replace({0.0 : "No", 1.0 : "Yes"})
dataclean_df.head()

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventBootcamp,CountryLive,EmploymentField,EmploymentStatus,Gender,HasChildren,HoursLearning,Income,JobRoleInterest,SchoolDegree,SchoolMajor
0,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,office and administrative support,Employed for wages,male,No,30,32000.0,NaN,"some college credit, no degree",NaN
1,22.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,food and beverage,Employed for wages,male,NaN,30,15000.0,Front-End Web Developer,"some college credit, no degree",NaN
2,19.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,finance,Employed for wages,male,NaN,20,48000.0,NaN,high school diploma or equivalent (GED),NaN
3,26.0,No,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,NaN,20,43000.0,Front-End Web Developer,bachelor's degree,Cinematography And Film
4,20.0,No,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,education,Employed for wages,female,NaN,25,6000.0,Full-Stack Web Developer,"some college credit, no degree",NaN

In [61]:
# Calculate total number of respondents in survey
number_respondents=len(dataclean_df)
print(number_respondents)

15620

In [62]:
# Extract rows corresponding only to people who attended a bootcamp
Attend_bootcamp = dataclean_df.loc[dataclean_df["AttendedBootcamp"] == "Yes"]
Attend_bootcamp.count()

Age                     818
AttendedBootcamp        953
BootcampFinish          933
BootcampFullJobAfter    635
BootcampLoanYesNo       934
BootcampPostSalary      330
BootcampRecommend       937
ChildrenNumber          148
CityPopulation          823
CodeEventBootcamp        27
CountryLive             825
EmploymentField         476
EmploymentStatus        792
Gender                  833
HasChildren             211
HoursLearning           925
Income                  430
JobRoleInterest         402
SchoolDegree            832
SchoolMajor             622
dtype: int64

In [95]:
# Calculate average age of attendees
mean_age = dataclean_df["Age"].mean()
print(mean_age)

# Calculate how many people attended a bootcamp
Boot_camp_attendees = Attend_bootcamp["AttendedBootcamp"].count()
print(Boot_camp_attendees)

#Calculate how many attendees hold degrees
Attendees_hold_degrees = Attend_bootcamp["SchoolDegree"].count()
print(Attendees_hold_degrees)

# Count number of attendees who self-identify as male; female; or are of non-binary gender identification
Gender_count = Attend_bootcamp['Gender'].count()
Male_count = Attend_bootcamp['Gender'].value_counts()["male"]
Female_count = Attend_bootcamp['Gender'].value_counts()["female"]
NonBinary_count = Gender_count-(Male_count + Female_count)
print(Gender_count)
print(Male_count)
print(Female_count)
print(NonBinary_count)

# Calculate percentage of respondents who attended a bootcamp
Percent_respondents = (Boot_camp_attendees/number_respondents)*100
print(Percent_respondents)

# Calculate percentage of respondents belonging to each gender
Male_Percent = (Male_count/number_respondents) * 100
Female_Percent = (Female_count/number_respondents) * 100
NonBinary_Percent = (NonBinary_count/number_respondents) * 100

# Calculate percentage of attendees with a school degree
School_degree_percent = (Attendees_hold_degrees/Boot_camp_attendees)*100

# Calculate average post-bootcamp salary
Avg_salary = Attend_bootcamp["BootcampPostSalary"].mean()
print(Avg_salary)

29.17542055388232
953
832
833
496
326
11
6.101152368758003
63740.50606060606

In [99]:
# Create a new table consolidating above calculations
new_df = pd.DataFrame([
    {"Average Salary": Avg_salary}, {"Percentage of School degree": School_degree_percent}, {"Male percent of respondents": Male_Percent}, {"Female percent of respondents": Female_Percent}, 
       {"NonBinary percent of respondents": NonBinary_Percent}, {"Number of people attending Bootcamp": Boot_camp_attendees}, 
    {"The number of attendees that hold degrees": Attendees_hold_degrees}, {"Average Age of Attendees": mean_age}])

# Improve formatting before outputting spreadsheet

pd.options.display.float_format = '${:,.2f}'.format

In [100]:
# Export to Excel
new_df.to_excel("output/DataCleanUp.xls", sheet_name='Sheet_name_1',index=False, header=True)